# Copyright (c) 2025, The Nav-Suite Project Developers (https://github.com/leggedrobotics/nav-suite/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from dataclasses import MISSING
from typing import Literal

from isaaclab.utils import configclass

from nav_suite.terrain_analysis import TerrainAnalysisCfg, TerrainAnalysisSingletonCfg

from .fix_goal_command import FixGoalCommand
from .goal_command_base_cfg import GoalCommandBaseCfg


@configclass
class FixGoalCommandCfg(GoalCommandBaseCfg):
    """Configuration for the terrain-based position command generator."""

    class_type: type = FixGoalCommand

    fix_goal_position: list[float] = MISSING
    """Fixed goal position in world frame relative to the terrain origin in [m]."""

    relative_terrain_origin: Literal["origin", "center"] = "origin"
    """Reference point of the different subterrains generated by the terrain generator. Default is "origin".

    In the case the terrain generator was used to create the terrain, then for each subterrain an origin is defined.
    The origin can be offsetted from the actual center of the subterrain. This parameter defines the reference point
    for the defined fix goal position.:

    - "origin": The origin of the subterrain is used as reference point.
    - "center": The center of the subterrain is used as reference point.

    .. note ::
        "center" is only available if the terrain generator was used. Otherwise, the origins are used per default.

    """

    goal_rand_x: tuple[float, float] = (0.0, 0.0)
    """Randomization range for the goal position in x-direction in [m]."""

    goal_rand_y: tuple[float, float] = (0.0, 0.0)
    """Randomization range for the goal position in y-direction in [m]."""

    start_rand: tuple[float, float] = (-0.2, 0.2)
    """Randomization range for the start position in x and y direction in [m]."""

    trajectory_num_samples: int | None = None
    """Restrict the number of samples for the trajectory analysis. Default is None.

    None means that the number of samples is not restricted. """

    project_onto_terrain: bool = False
    """Project the goal position onto the terrain surface. Default is False.

    This will run the :func:`nav_suite.terrain_analysis.TerrainAnalysis.construct_height_map` function."""

    terrain_analysis: TerrainAnalysisCfg | TerrainAnalysisSingletonCfg = TerrainAnalysisCfg()
    """Configuration for the trajectory analysis used to get the terrain height for the goal point projection."""
